export * from "./admin";
export * from "./user-type";
export * from "./seller-type";
export * from "./customer-type";
export * from "./product-data-type";
export * from "./api-respones-type";
export * from "./signup-response-type";
export * from "./add-product-data-type";
export * from "./single-product-data-type";
